version: 0.2
env:
  parameter-store:
    ARTIFACTORY_API_KEY: JFRPG_API
phases:
  install:
     commands:
      - echo Entering install phase...
      - wget https://dlcdn.apache.org/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.tar.gz 
      - tar xzvf apache-maven-3.8.5-bin.tar.gz -C /opt/
      - export PATH=/opt/apache-maven-3.8.5/bin:$PATH
      - wget -qO - https://releases.jfrog.io/artifactory/jfrog-gpg-public/jfrog_public_gpg.key | sudo apt-key add -
      - echo "deb https://releases.jfrog.io/artifactory/jfrog-debs xenial contrib" | sudo tee -a /etc/apt/sources.list;
      - apt update;
      - apt install -y jfrog-cli-v2-jf;
     
      
  pre_build:
     env:
      variables:
         ARTIFACTORY_URL: 'https://testgl.jfrog.io/ui/repos/tree/General/'
         ARTIFACTORY_USER: 'madhuric132@gmail.com'
         ARTIFACTORY_MVN_REPO: 'https://testgl.jfrog.io/ui/repos/tree/General/default-maven-virtual'
     commands:
        - echo Entering pre_build phase...
        - echo ${ARTIFACTORY_API_KEY}
        - echo $ARTIFACTORY_URL
        # - jf config add --url $ARTIFACTORY_URL --user ${ARTIFACTORY_USER} --apikey ${ARTIFACTORY_API_KEY}
        - jf config add --interactive=false --url $ARTIFACTORY_URL
        - jf c show
        - jf config add --access-token ${ARTIFACTORY_API_KEY} --interactive=false
        - sed -i -e 's|ARTIFACTORY_USER|${ARTIFACTORY_USER}|g' setting.xml && sed -i -e 's|ARTIFACTORY_PASSWORD|${ARTIFACTORY_API_KEY}|g' setting.xml && sed -i -e 's|ARTIFACTORY_MVN_REPO|${ARTIFACTORY_MVN_REPO}|g' setting.xml
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - mvn -s setting.xml -f pom.xml compile
      - mvn -s setting.xml -f pom.xml package 
     
  post_build:
    commands:
      - echo Entering post_build phase...
      - echo Build completed on `date`i
      - jf rt u "*.war" libs-release-local --build-name=awslab1 --build-number=$CODEBUILD_BUILD_ID --flat=false
      - jf rt bce awslab1 $CODEBUILD_BUILD_ID
      - jf rt bp awslab1 $CODEBUILD_BUILD_ID
artifacts:
  type: zip
  files:
    - 'appspec.yml'
    - 'scripts/start_server'
    - 'scripts/install_dependencies'
    - 'target/ROOT.war'
